data:
    dataset_path: "debug_dataset"
    dataset_split_path: "data_split.json"
    # input_modalities: ["odom", "imu", ]
    # prediction: ["controls"]
    horizon_seconds:
        train: 1.6
        val: 1.8
        test: 2.0
    dt: 0.1
    modalities:
        super_odom:
            type: state
            frequency: 100
            description: "Super Odometry"
        cmd:
            type: action
            frequency: 10
            description: "Control Input"
        traversability_cost:
            type: environment
            frequency: 100
            description: "Traversability Cost"
        traversability_breakdown:
            type: environment
            frequency: 100
            description: "Traversability Breakdown"
        wheel_rpm:
            type: environment
            frequency: 50
            description: "Wheel RPM"

train:
    batch_size: 64
    max_epochs: 12
    learning_rate: 0.0001
    optimizer: "adam"
    loss: "mse"
    train_split: 0.5
    accuracy: "mse"

model:
    type: "simple_mlp" # "seq2seq"
    hidden_size: 128
    num_layers: 2
    nhead: 4

seed: 4
fast_dev_run: False
