data:
    dataset_path: "debug_dataset"
    # input_modalities: ["odom", "imu", ]
    prediction: ["controls"]
    horizon: 2
    dt: 0.1
    modalities:
        super_odom:
            type: state
            frequency: 100
            description: "Super Odometry"
        cmd:
            type: action
            frequency: 10
            description: "Control Input"

train:
    batch_size: 128
    max_epochs: 15
    learning_rate: 0.0001
    optimizer: "adam"
    loss: "mse"
    train_split: 0.5
    accuracy: "mse"
model:
    hidden_size: 128
    num_layers: 2
seed: 4
fast_dev_run: False
