data:
    dataset_path: "debug_dataset"
    # input_modalities: ["odom", "imu", ]
    prediction: ["controls"]
    horizon: 2
    dt: 0.1
    modalities:
        super_odom:
            type: state
            frequency: 100
            description: "Super Odometry"
        cmd:
            type: action
            frequency: 10
            description: "Control Input"

train:
    batch_size: 32
    epochs: 100
    learning_rate: 0.001
    optimizer: "adam"
    loss: "mse"
    train_split: 0.5
test:
seed: 42