data:
    dataset_path: "/ocean/projects/cis220039p/shared/tartandrive/2023_traj/v1"
    dataset_split_path: "data_split_full.json"
    # input_modalities: ["odom", "imu", ]
    # prediction: ["controls"]
    horizon_seconds:
        train: 1.6
        val: 1.8
        test: 2.0
    dt: 0.1
    modalities:
        super_odom:
            type: state
            frequency: 100
            description: "Super Odometry"
        cmd:
            type: action
            frequency: 10
            description: "Control Input"
        traversability_cost:
            type: environment
            frequency: 100
            description: "Traversability Cost"
        traversability_breakdown:
            type: environment
            frequency: 100
            description: "Traversability Breakdown"
        wheel_rpm:
            type: environment
            frequency: 50
            description: "Wheel RPM"
        height_map_12x12:
            type: environment
            frequency: 10
            description: "Height Map 4 channel"
        image_left_color:
            type: environment
            frequency: 10
            description: "PNG Images from left camera"
        

train:
    batch_size: 128
    max_epochs: 5
    learning_rate: 0.005
    optimizer: "adam"
    loss: "mse"
    train_split: 0.8
    accuracy: "mse"
    num_workers: 4

model:
    type: "transformer" # "simple_mlp"  "seq2seq"
    hidden_size: 64
    num_layers: 2
    nhead: 4
    pretrained: True
    use_decoder: False

seed: 4
fast_dev_run: False
